DROP TABLE IF EXISTS vendor, txn, app_user, acct, category;

CREATE TABLE vendor (
    id bigint generated by default as IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL,
    website varchar(30) NOT NULL
);

CREATE TABLE app_user (
    id bigint generated by default as IDENTITY PRIMARY KEY,
    first_name varchar(30),
    last_name varchar(30),
    email varchar(254) NOT NULL UNIQUE,
    password TEXT NOT NULL
);

CREATE TABLE acct (
    id bigint generated by default as IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL,
    app_user_id int,
    FOREIGN KEY (app_user_id) REFERENCES app_user(id)
);

CREATE TABLE category(
    id bigint generated by default as IDENTITY PRIMARY KEY,
    name varchar(30)
);

CREATE TABLE txn (
    id bigint generated by default as IDENTITY PRIMARY KEY,
    description varchar(120) NOT NULL,
    vendor_id int,
    amount numeric(20, 2) NOT NULL,
    category int,
    pending boolean,
    txn_date date NOT NULL,
    acct_id int NOT NULL,
    FOREIGN KEY (vendor_id) REFERENCES vendor(id),
    FOREIGN KEY (category) REFERENCES category(id),
    FOREIGN KEY (acct_id) REFERENCES acct(id)
);