DROP TABLE IF EXISTS vendor, txn, acct, acct_types, category;

CREATE TABLE vendor (
    id bigint generated by default as IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    website TEXT NOT NULL,
    logo TEXT
);

CREATE TABLE acct_types (
    id bigint generated by default as IDENTITY PRIMARY KEY,
    name varchar(20)
);

INSERT INTO acct_types (name) VALUES
('Checking'), ('Saving'), ('Credit Card'), ('Investment'), ('Retirement'), ('Loan');

CREATE TABLE acct (
    id bigint generated by default as IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    acct_type_id int,
    description TEXT,
    app_user_id int,
    FOREIGN KEY (acct_type_id) REFERENCES acct_types(id),
    FOREIGN KEY (app_user_id) REFERENCES app_user(id)
);

CREATE TABLE category(
    id bigint generated by default as IDENTITY PRIMARY KEY,
    name varchar(30),
    description TEXT
);

CREATE TABLE txn (
    id bigint generated by default as IDENTITY PRIMARY KEY,
    description TEXT NOT NULL, -- Bank description of the transation, can be adjusted by the user
    notes TEXT, -- notes from the user on the transaction (i.e. "Gift for mom")
    vendor_id int,
    amount numeric(20, 2) NOT NULL,
    category int,
    pending boolean,
    txn_date date NOT NULL,
    acct_id int NOT NULL,
    FOREIGN KEY (vendor_id) REFERENCES vendor(id),
    FOREIGN KEY (category) REFERENCES category(id),
    FOREIGN KEY (acct_id) REFERENCES acct(id)
);