DROP TABLE IF EXISTS app_user;


CREATE TABLE app_user (
    id bigint generated by default as IDENTITY PRIMARY KEY,
    first_name varchar(30),
    last_name varchar(30),
    email varchar(254) NOT NULL UNIQUE,
    password TEXT NOT NULL
);