FROM node:20

# Set working dir to root of monorepo
WORKDIR /app

# Copy entire monorepo into container
COPY . .

# Install dependencies
RUN npm install
# Set working dir to the API package
WORKDIR /app/packages/api

# Expose the API port
EXPOSE 3001

# Start the dev server
CMD ["npm", "run", "dev"]
