FROM node:20

# Set working directory
WORKDIR /app/packages/api

# Install dependencies
COPY package*.json ../../
COPY ../.. /app

# Expose the API port
EXPOSE 3001 9229

# Start the dev server
CMD ["npm", "run", "dev"]
