services:
  db:
    image: postgres:16
    container_name: astra-dev-db
    environment:
      POSTGRES_USER: astra
      POSTGRES_PASSWORD: 4stra!
      POSTGRES_DB: astradb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  frontend:
    build:
      context: ../
      dockerfile: ./containers/Dockerfile.ui
    container_name: vite-frontend
    ports:
      - "5173:5173"
    volumes:
      - ../packages/ui:/app
      - /app/node_modules  # ensures host node_modules doesn't overwrite container's
    networks:
      - app-network
    environment:
      - NODE_ENV=development



volumes:
  pgdata:

networks:
  app-network:
